name: sipur
description: "Create your own sipur."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
#  chat_gpt_sdk: 3.0.4

  cupertino_icons: ^1.0.6
  go_router: ^13.2.0
  firebase_auth: ^4.17.8
  cloud_functions: ^4.6.8
  firebase_core: ^2.27.0
  firebase_ui_auth: ^1.13.1
  firebase_ui_oauth_google: ^1.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true


fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf