// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ1w1tvTUPugjUt1TRuLgBII-hc5qhNWk',
    appId: '1:209098881200:web:8c5708b5c1a892dc82a375',
    messagingSenderId: '209098881200',
    projectId: 'sipur-ai',
    authDomain: 'sipur-ai.firebaseapp.com',
    databaseURL: 'https://sipur-ai-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sipur-ai.appspot.com',
    measurementId: 'G-FG37ZLV98N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoVS9w1hrWE-ky_mQc2cMFb-5T-j2RzAA',
    appId: '1:209098881200:android:a0b8287f185f1d1d82a375',
    messagingSenderId: '209098881200',
    projectId: 'sipur-ai',
    databaseURL: 'https://sipur-ai-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sipur-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDktAgQ8Y-Aa39ueIqHG0GcqcD613UHtvM',
    appId: '1:209098881200:ios:5d5a02fe1e788f5182a375',
    messagingSenderId: '209098881200',
    projectId: 'sipur-ai',
    databaseURL: 'https://sipur-ai-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sipur-ai.appspot.com',
    iosBundleId: 'com.example.sipur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDktAgQ8Y-Aa39ueIqHG0GcqcD613UHtvM',
    appId: '1:209098881200:ios:44e3a3d5cae5685082a375',
    messagingSenderId: '209098881200',
    projectId: 'sipur-ai',
    databaseURL: 'https://sipur-ai-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sipur-ai.appspot.com',
    iosBundleId: 'com.example.sipur.RunnerTests',
  );
}
